# Generated by Django 4.2.20 on 2025-05-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='movement_type',
            new_name='type',
        ),
    ]
