# Generated by Django 4.2.20 on 2025-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_movement_type_transactions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='created_at',
        ),
    ]
