# Generated by Django 4.2.20 on 2025-05-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
    ]
